### ISSUE TITLE
查询presentable列表时，不可以获知哪一个presentable需要付费

### ISSUE THREAD

**Issue by Wweizhi** [freelogfe/freelog-component-template#5]
问题描述：节点获取presentable的授权状态，须要请求presentable详情；例如，有一个音频列表，每个音频都几M的大小，为了获取授权信息，所有音频都请求一遍，成本十分高，不合理。

**Comment by daizch** [comment]
后端提供单个presentable的授权查询,后续再考虑在中间代理层封装批量查询接口。
